version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - run:
          environment:
            MYPYPATH: stubs
          command: |
            sudo pip install pipenv
            pipenv install --dev
            pipenv run make test
            pipenv run coverage run --source ietfdata tests/test_rfcindex.py
            pipenv run coverage run -a --source ietfdata tests/test_datatracker.py 
            pipenv run coverage report
            pipenv run coverage html
          name: Test
      - store_artifacts:
          path: htmlcov

workflows:
  main:
    jobs:
      - build-and-test
