version: 2.1

orbs:
  python: circleci/python@2.0.3

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - run:
          environment:
            MYPYPATH: stubs
          command: |
            pipenv install --dev
            pipenv run make test
            pipenv run coverage run --source ietfdata tests/test_rfcindex.py
            pipenv run coverage run -a --source ietfdata tests/test_datatracker.py
            pipenv run coverage report
            pipenv run coverage html
          name: Test
      - store_artifacts:
          path: htmlcov

  build-and-test-mongodb:
    docker:
      - image: cimg/python:3.9
      - image: circleci/mongo:4.4.22
    steps:
      - checkout
      - run:
          environment:
            MYPYPATH: stubs
            IETFDATA_CACHE_HOST: localhost
          command: |
            pipenv install --dev
            pipenv run make test
            pipenv run make test
          name: Test-Cache
      - store_artifacts:
          path: htmlcov

workflows:
  main:
    jobs:
      - build-and-test
      - build-and-test-mongodb
